version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_Db: whale_db

  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

#  api:
#    build:
#      dockerfile: Dockerfile
#      context: ./
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgresql://postgres:5432/whale_db
#      DATABASE_USER: root
#      DATABASE_PASSWORD: root
#    ports:
#      - "8080:3100"

